### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by Rudis1261**
- Adding some instructions on how to get started.
- Home assistant example configuration and dashboard yaml files.
- Moved firmware into a specific folder and reorganized it slightly.

### CODE REVIEW

**Comment by Rudis1261** [comment]
@jackkitley 😬 Hope you like these updates, lemme know

**Comment by jackkitley** [comment]
@Rudis1261 Thank you for this. Whats your profession ?

**Comment by Rudis1261** [comment]
Awesome, if you are happy with the updates you can merge them / approve the pull request. 

I am a web developer by trade 😬

**Comment by jackkitley** [comment]
@Rudis1261 Thanks. ill have a look at them this eve.
Please whatsapp me on 0.8.2 5.9.0 2.1.4.7

**Pull request merged**
